
<div data-bind="scope: 'hello'">

    <p data-bind="html: helloMessage"></p>

    <ul data-bind="foreach: helloArray">
        <li data-bind="text: $data"></li>
    </ul>

    <!-- ko if: helloArray.length -->
    <ul>
        <!-- ko foreach: { data: helloArray, as: 'item' } -->
        <li><!-- ko text: item --><!-- /ko --></li>
        <!-- /ko -->
    </ul>
    <!-- /ko -->

</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "hello": {
                        "component": "Inchoo_UiExamples/js/view/example4",
                        "config": { "a": 1, "b": 2 }
                    }
                 }
            }
        }
    }
</script>
