<p id="test1">test1.phtml template</p>

<div data-bind="scope: 'hello'">

    <div data-bind="html: helloMessage"></div>

    <ul data-bind="foreach: helloArray">
        <li data-bind="text: $data"></li>
    </ul>

    <!-- ko if: helloArray.length -->
    <ul>
        <!-- ko foreach: { data: helloArray, as: 'item' } -->
        <li><!-- ko text: item --><!-- /ko --></li>
        <!-- /ko -->
    </ul>
    <!-- /ko -->

</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "hello": {
                            "component": "Inchoo_UiExamples/js/view/hello"
                        }
                    }
                }
            }
    }
</script>
